name: sardana-jupyter
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - notebook
  - ipywidgets
  - pytango
  - click
  - itango
  - lxml
  - pyyaml
  - ipykernel
  - jupyterlab
  - pip
  - nodejs
  - jupyter-dash
  - plotly
  - pandas
  - dash-core-components 
  - dash-html-components
  - pip:
    - --editable=./
    - --editable=file:///home/mespin/Work/zreszela-taurus
    - --editable=file:///home/mespin/Work/sardana-ms-events