name: sardana-jupyter
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - notebook
  - ipywidgets
  - pytango
  - click
  - itango
  - lxml
  - pyyaml
  - ipykernel
  - jupyterlab
  - pip
  - nodejs
  - pip:
    - --editable=../
    - --editable=file:///taurus/
    - --editable=file:///sardana/